#!/usr/bin/env python3
"""Check that the implementation matches docs/specs.

Two passes. This script is the first: everything that can be decided without a model,
which is most of the bookkeeping a spec carries. Clause numbering, the tests a clause
names, the paths it governs, the symbols it guards, and the table in the specs README
are all facts, and a fact does not need a review.

    check-spec.py --mechanical-only          the whole first pass, human readable
    check-spec.py --mechanical-only labels   one spec, by name or by id
    check-spec.py --changed                  only specs governing what this branch touched
    check-spec.py --write-unverified         write agents/unverified-clauses.txt from the spec tree

Run with neither --mechanical-only nor --list it also prepares the second pass: a work
directory holding one prompt file per group of clauses, for the conformance review the
check-spec skill drives. Nothing about that pass is decided here; this script writes
files and prints a pointer to them.
"""

import argparse
import json
import os
import re
# Only ever invoked with an argument list, never a shell string.
import subprocess  # nosemgrep: gitlab.bandit.B404
import sys
import tempfile
from datetime import datetime, timezone
from fnmatch import fnmatch
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from specs import EM_DASH, README, SPEC_DIR, TestIndex, crate_directories, load_specs  # noqa: E402

ERROR = "error"
WARNING = "warning"

# `reads_a_step_without_keying` is read by the security-audit skill rather than here: it names the
# functions that read a `Step` field by field for something that is not a key, which that skill
# otherwise faults. It is listed so a deliberate key is told apart from a `sites:` indented out of
# its `guards` entry, which is what the unknown-key error is for.
FRONT_MATTER_KEYS = {
    "id",
    "title",
    "status",
    "governs",
    "guards",
    "documented-by",
    "reads_a_step_without_keying",
}

UNVERIFIED_FILE = Path("agents/unverified-clauses.txt")

UNVERIFIED_HEADER = """\
# Spec clauses whose verified-by value is none.
# Generated by make write-unverified. Give a clause a test rather than editing here: while the two
# disagree, make check-spec fails.
# Source: docs/specs/**/*.md, one line per clause, as path:CLAUSE-ID: heading.
# Withdrawn clauses carry no verified-by line at all and are not listed.
# No count is kept here. Two branches that each verify a clause both edit the count, so it conflicts
# where the lists themselves merge cleanly, and a count nothing reads is wrong quietly. Count the
# lines, or read the warnings check-spec prints.
"""


def finding(spec, severity, kind, summary, clause=None, evidence=None, fix=None):
    return {
        "spec": spec,
        "clause": clause,
        "severity": severity,
        "kind": kind,
        "summary": summary,
        "evidence": evidence,
        "fix": fix,
        "source": "mechanical",
    }


def check_front_matter(spec):
    if spec.malformed_front_matter:
        yield finding(
            spec.rel,
            ERROR,
            "front-matter-malformed",
            "front matter is not the scalar-and-list shape the specs README describes",
        )
        return
    for required in ("id", "title", "status"):
        if not spec.front.get(required):
            yield finding(
                spec.rel, ERROR, "front-matter-missing", f"front matter has no `{required}`"
            )
    if not spec.governs:
        yield finding(
            spec.rel,
            ERROR,
            "front-matter-missing",
            "front matter lists no `governs` paths, so no diff is ever reviewed against it",
        )
    for name in sorted(set(spec.front) - FRONT_MATTER_KEYS):
        yield finding(
            spec.rel,
            ERROR,
            "front-matter-unknown-key",
            f"front matter has a `{name}` key, which nothing reads",
            fix="a `sites:` indented out of its `guards` entry lands here and pins nothing",
        )


def check_clause_numbering(spec):
    seen = {}
    expected = 1
    for clause in spec.clauses:
        if clause.prefix != spec.id:
            yield finding(
                spec.rel,
                ERROR,
                "clause-prefix-mismatch",
                f"clause is `{clause.id}` in a spec whose id is `{spec.id}`",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line}",
            )
        if clause.number in seen:
            yield finding(
                spec.rel,
                ERROR,
                "clause-duplicate",
                f"`{clause.id}` appears twice, and an id points at one clause forever",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line} and {spec.rel}:{seen[clause.number]}",
            )
        seen[clause.number] = clause.line
        if clause.number != expected:
            yield finding(
                spec.rel,
                ERROR,
                "clause-numbering",
                f"`{clause.id}` follows {expected - 1}: ids are allocated in order and never renumbered",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line}",
                fix="a withdrawn clause stays in place, marked withdrawn, rather than leaving a gap",
            )
        expected = max(expected, clause.number) + 1
        if clause.withdrawn and "replaced" not in clause.text.lower():
            yield finding(
                spec.rel,
                ERROR,
                "withdrawn-without-replacement",
                f"`{clause.id}` is withdrawn but does not say what replaced it",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line}",
            )


def check_coverage(spec, index, crates):
    for clause in spec.clauses:
        if clause.withdrawn:
            continue
        if not clause.verified_by:
            yield finding(
                spec.rel,
                ERROR,
                "clause-unverified",
                f"`{clause.id}` names no test at all: every clause carries a `verified-by` line",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line}",
            )
            continue
        for reference in clause.verified_by:
            if reference == "none":
                yield finding(
                    spec.rel,
                    WARNING,
                    "clause-uncovered",
                    f"`{clause.id}` is `verified-by: none`, so nothing pins it",
                    clause=clause.id,
                    evidence=f"{spec.rel}:{clause.line}",
                    fix="write the test, or say by-construction with the reason in brackets",
                )
                continue
            if reference.startswith("by-construction"):
                rest = reference[len("by-construction") :].strip()
                bracketed = (rest[:1], rest[-1:]) in (("(", ")"), ("[", "]"))
                if not (bracketed and len(rest) > 2):
                    yield finding(
                        spec.rel,
                        ERROR,
                        "by-construction-unexplained",
                        f"`{clause.id}` says by-construction without saying in brackets what makes it hold",
                        clause=clause.id,
                        evidence=f"{spec.rel}:{clause.line}",
                    )
                continue
            status, detail = index.resolve(reference, crates)
            if status == "ok":
                continue
            if status == "moved":
                yield finding(
                    spec.rel,
                    ERROR,
                    "verified-by-moved",
                    f"`{clause.id}` names `{reference}`, but that test lives elsewhere now",
                    clause=clause.id,
                    evidence=detail,
                    fix="update the path in the spec, or move the test back to the module it belongs to",
                )
            elif status == "missing":
                yield finding(
                    spec.rel,
                    ERROR,
                    "verified-by-missing",
                    f"`{clause.id}` names `{reference}`, and no `#[test]` by that name exists",
                    clause=clause.id,
                    evidence=f"{spec.rel}:{clause.line}",
                )
            elif status == "unknown-crate":
                yield finding(
                    spec.rel,
                    ERROR,
                    "verified-by-unknown-crate",
                    f"`{clause.id}` names crate `{detail}`, which is not in this workspace",
                    clause=clause.id,
                    evidence=f"{spec.rel}:{clause.line}",
                )
            else:
                yield finding(
                    spec.rel,
                    ERROR,
                    "verified-by-malformed",
                    f"`{clause.id}` names `{reference}`, which is not `crate::module::test_name`",
                    clause=clause.id,
                    evidence=f"{spec.rel}:{clause.line}",
                )


def unverified_clauses(specs, index, crates):
    """The clauses the coverage check calls uncovered, in the form the committed file lists.

    The set is `check_coverage`'s own rather than a second reading of `verified-by`, so the file
    holds what the warnings hold. A withdrawn clause carries no `verified-by` line at all, and
    stays out of both by the same code."""
    uncovered = {
        (found["spec"], found["clause"])
        for spec in specs
        for found in check_coverage(spec, index, crates)
        if found["kind"] == "clause-uncovered"
    }
    return [
        f"{spec.rel}:{clause.id}: {clause.title}"
        for spec in specs
        for clause in spec.clauses
        if (spec.rel, clause.id) in uncovered
    ]


def render_unverified(lines):
    return UNVERIFIED_HEADER + "\n" + "".join(f"{line}\n" for line in lines)


def listed_unverified(text):
    """The `path:CLAUSE-ID` of each clause a written form lists, so two forms can be compared
    by what they say rather than only by their bytes."""
    return {
        line.split(": ", 1)[0] for line in text.split("\n") if line and not line.startswith("#")
    }


def check_documentation(spec, website_docs=Path("docs/website/docs")):
    """Which pages on the site describe this spec, decided once per spec.

    Per spec rather than per clause. A page is written for somebody with a task, so it covers a
    topic and rarely lines up with one clause: a clause-by-clause answer is hundreds of rows
    nobody reads, where one row per file is a question somebody can sit down and answer. The
    price is that the check cannot tell a spec half described from one described fully, which is
    a judgement a reader of the page has to make anyway.

    Paths are from the repository root, the same root `governs` writes, so one front matter never
    means two different things by a path.
    """
    references = spec.documented_by
    if not references:
        yield finding(
            spec.rel,
            ERROR,
            "spec-undocumented",
            "front matter has no `documented-by`, so nothing records whether the site covers this",
            fix="name the pages under docs/website/docs/ that describe it, "
            "or `none` with the reason in brackets",
        )
        return
    for reference in references:
        if reference.startswith("none"):
            rest = reference[len("none") :].strip()
            bracketed = (rest[:1], rest[-1:]) in (("(", ")"), ("[", "]"))
            if not (bracketed and len(rest) > 2):
                yield finding(
                    spec.rel,
                    ERROR,
                    "none-unexplained",
                    "`documented-by: none` does not say in brackets why the site needs no page "
                    "for this",
                    fix="`none (internal: ...)` for behaviour no reader acts on, "
                    "`none (gap: ...)` for a page still owed",
                )
            continue
        target = Path(reference.split("#", 1)[0].strip())
        if website_docs not in target.parents or not target.is_file():
            yield finding(
                spec.rel,
                ERROR,
                "documented-by-missing",
                f"`documented-by` names `{reference}`, which is not a page under `{website_docs}`",
                fix=f"write the path from the repository root, as `{website_docs}/...`, "
                f"and create the page if it is not there yet",
            )


def check_unverified_file(specs, index, crates):
    """The committed list of uncovered clauses is the one a run generates.

    Nothing else reads that file. Without this a clause given `verified-by: none` lands as a
    warning in a log nobody keeps, and the tracked file stays as it was, so the number of
    clauses nothing pins goes up without appearing in any diff."""
    generated = render_unverified(unverified_clauses(specs, index, crates))
    committed = UNVERIFIED_FILE.read_text(encoding="utf-8") if UNVERIFIED_FILE.exists() else ""
    if committed == generated:
        return
    listed = listed_unverified(committed)
    live = listed_unverified(generated)
    detail = []
    if live - listed:
        detail.append(f"nothing pins {', '.join(sorted(live - listed))}")
    if listed - live:
        detail.append(f"a test now pins {', '.join(sorted(listed - live))}")
    yield finding(
        str(UNVERIFIED_FILE),
        ERROR,
        "unverified-list-stale",
        f"{UNVERIFIED_FILE} is not the list this tree generates",
        evidence="; ".join(detail) or "the same clauses, written another way",
        fix="make write-unverified, and commit what it writes",
    )


def partial_selection(selectors, changed_base):
    """Whether a run was asked for part of the spec tree.

    `agents/unverified-clauses.txt` is a statement about every spec, so a run given a filter is refused
    rather than served: writing what the filter saw drops every spec it did not name, and writing
    the whole tree anyway makes the file the answer to a question nobody asked."""
    return bool(selectors) or changed_base is not None


def check_anchors(spec):
    """A clause id is what an issue, a commit and a test name all point at, so it has to be
    possible to link to one. The anchor a heading generates carries its title and breaks the
    next time somebody rewords it, which is why the id gets an anchor of its own."""
    for clause in spec.clauses:
        wanted = f'<a id="{clause.id}"></a>'
        above = spec.lines[clause.line - 2].strip() if clause.line >= 2 else ""
        if above != wanted:
            yield finding(
                spec.rel,
                ERROR,
                "clause-anchor-missing",
                f"`{clause.id}` has no `{wanted}` on the line above its heading",
                clause=clause.id,
                evidence=f"{spec.rel}:{clause.line}",
                fix="without it, a link into this clause breaks when the heading is reworded",
            )


def check_governs(spec):
    for pattern in spec.governs:
        if any(character in pattern for character in "*?["):
            if not list(Path().glob(pattern)):
                yield finding(
                    spec.rel,
                    ERROR,
                    "governs-missing",
                    f"`governs` pattern `{pattern}` matches nothing",
                )
        elif not Path(pattern).exists():
            yield finding(
                spec.rel,
                ERROR,
                "governs-missing",
                f"`governs` names `{pattern}`, which does not exist",
                fix="a rename that leaves governs behind quietly stops the spec reviewing anything",
            )


_STRIPPED = {}

# The first parameter of a method, in every shape Rust writes it: `self`, `&self`, `&mut self`,
# `&'a self`, `mut self`, `self: Box<Self>`.
RECEIVER = re.compile(r"\s*&?\s*(?:'[a-z_]\w*\s+)?(?:mut\s+)?self\b")

# A line beginning something, as against one continuing the line above it. An `impl` whose bounds
# or `where` clause run to several lines is the same item on each of them, and rustfmt leaves the
# brace that opens its block alone on a line of its own.
ITEM = re.compile(
    r"(?:pub|impl|fn|mod|struct|enum|trait|type|const|static|use|unsafe|async|extern)\b"
    r"|macro_rules!|#\[|\}"
)

# An item that opens a block a definition inside it belongs to: the `impl` that makes a `fn` a
# method of a type, and the `mod` that makes one a function of a module. `pub` and `pub(crate)`
# come in front of a `mod` and never in front of an `impl`.
BLOCK = re.compile(r"(?:pub(?:\([^)]*\))?\s+)?(?:impl|mod)\b")


def strip_comments(lines):
    """The same lines with their comments blanked out, since a symbol named in prose is not a
    use of it. Half the lines naming `Policy::present` are the trust argument written around
    the gate rather than calls to it, and counting those would make the allowlists below a
    record of the documentation that fails on every reworded sentence.

    Held by content, because `guard_sites` needs this for every symbol it counts and the answer
    depends on nothing else. The work below is a character at a time over every file in the tree,
    so a run counting a dozen symbols spent a dozen passes producing the same lines.

    Line comments are cut wherever they start rather than only at the margin, block comments
    are followed across lines, and a `//` inside a string stays: all three shapes are in the
    files whose counts are pinned, and a stripper that got any of them wrong would move a
    count without anybody touching a call.

    A string is not followed across lines. Rust has such strings, but one holding an unclosed
    `/*` would have to be for this to matter, and the counts are checked against the tree."""
    held = "\n".join(lines)
    if held in _STRIPPED:
        return _STRIPPED[held]

    stripped = []
    in_block = False
    for raw in lines:
        kept = []
        in_string = False
        i = 0
        while i < len(raw):
            pair = raw[i : i + 2]
            if in_block:
                if pair == "*/":
                    in_block = False
                    i += 2
                    continue
                i += 1
                continue
            if in_string:
                if raw[i] == "\\":
                    i += 2
                    continue
                in_string = raw[i] != '"'
                kept.append(raw[i])
                i += 1
                continue
            if pair == "//":
                break
            if pair == "/*":
                in_block = True
                i += 2
                continue
            in_string = raw[i] == '"'
            kept.append(raw[i])
            i += 1
        stripped.append("".join(kept))
    _STRIPPED[held] = stripped
    return stripped


def definition_of(bare):
    """`fn <bare>` through the parenthesis that opens its parameters.

    The generics in between may hold one level of their own, which is as deep as
    `fn new<S: Into<String>>(` goes and as deep as this tree goes. Stopping at the parenthesis
    rather than in front of the generics is what lets a caller read the first parameter off
    whatever follows the match."""
    return re.compile(rf"\bfn\s+{re.escape(bare)}\s*(?:<[^<>]*(?:<[^<>]*>[^<>]*)*>)?\s*\(")


def its_own_file(path, qualifier):
    """Whether `path` is the file the module `qualifier` is.

    A free function at the margin of `home.rs` is `home::write_file` whether or not any line of
    that file spells the module's name, which is the one thing a file cannot be asked about by
    searching its text."""
    return path.stem == qualifier or (path.stem == "mod" and path.parent.name == qualifier)


def owned_definitions(bare, qualifier, sources):
    """The definitions of `bare` that `qualifier` owns, as `(path, number, receiver, in_impl)`,
    up to the first one in an `impl` that takes a receiver.

    A qualifier owns a definition in one of two ways. `Type::name` is defined in an `impl` naming
    the type. `module::name` is a free function, at the margin of a file of that name or inside a
    `mod` block of it, which is where a module-qualified guard like `home::write_file` lives.

    Owning it is what makes a qualified guard present at all, and the bare name alone is not:
    where `dispatched` is a method of the watch list and of nothing else, a guard on
    `Running::dispatched` names a symbol no type defines and has to come back empty. Reading the
    bare name instead lets a renamed method collect another type's call sites, and reports a
    guard nothing is left under as heavily used, which is the one answer this check must never
    give.

    Which block a definition sits in is read from the indentation: it belongs to the nearest
    `impl` or `mod` above it that is indented less far, and an item at that indentation or further
    out has closed that block. An `impl Labelled`, a later `fn` of the same name at the margin,
    and a `mod tests` with a `Latch::new` of its own are three blocks, and taking the last one
    seen would read them as one.

    Whether a definition takes a receiver is read off the definition rather than declared in the
    front matter, so a `guards` entry cannot assert that a method is an associated function and
    quietly drop the receiver form from what is counted."""
    definition = definition_of(bare)
    names_it = re.compile(rf"\b{re.escape(qualifier)}\b")
    module = re.compile(rf"\bmod\s+{re.escape(qualifier)}\b")
    found = []
    for path, lines in sources.items():
        code = strip_comments(lines)
        # A free function is owned by the file it is in. Anything else needs the block naming
        # the qualifier to be here, and most files in the tree never mention it.
        its_file = its_own_file(path, qualifier)
        if not its_file and not any(qualifier in line for line in code):
            continue
        blocks = []
        for number, raw in enumerate(code, start=1):
            body = raw.lstrip()
            if ITEM.match(body):
                indent = len(raw) - len(body)
                while blocks and blocks[-1][0] >= indent:
                    blocks.pop()
                if BLOCK.match(body):
                    blocks.append((indent, body))
            hit = definition.search(raw)
            if not hit:
                continue
            block = blocks[-1][1] if blocks else None
            if block is None:
                in_impl = False
                if not its_file:
                    continue
            elif block.startswith("impl"):
                in_impl = True
                if not names_it.search(block):
                    continue
            else:
                in_impl = False
                if not module.search(block):
                    continue
            # rustfmt puts the receiver on the next line wherever the signature does not fit.
            tail = raw[hit.end() :] + " " + (code[number] if number < len(code) else "")
            receiver = bool(RECEIVER.match(tail))
            found.append((path, number, receiver, in_impl))
            if receiver and in_impl:
                # Both questions a caller asks are settled: the qualifier owns the name, and it
                # is written with a receiver, so no definition after this one changes the answer.
                # Most guards here are methods, and stopping is the difference between reading
                # one crate and reading the tree once per guarded symbol.
                return found
    return found


def associated_sites(owned):
    """The definitions to count for `owned`, or `None` where the name is written with a receiver.

    Which of the two it is decides how a use can be written, and so what counting one means. A
    method is `receiver.name(` at nearly every call site, so those have to be counted. An
    associated function cannot be written that way at all, and counting the form anyway counts
    every `x.name(` on every other type in the tree. The `fn name` form fails the same way round
    the other side: a crate holding a dozen constructors says `fn new` a dozen times, one of them
    is the guarded one, and a count over all of them moves when an unrelated type gains one.

    `None` for a free function too, which no `impl` carries. A module path names no type, so
    nothing about the name says whether a use is written on a receiver, and a free function is
    counted the loose way a method is: `.name(` on any receiver joins its count, which is why
    `goal::read` reports every read in the tree."""
    inside = [(path, number, receiver) for path, number, receiver, in_impl in owned if in_impl]
    if any(receiver for _, _, receiver in inside):
        return None
    return {(path, number) for path, number, _ in inside} or None


def guard_sites(symbol, sources):
    """Every use of a guarded symbol, as `(path, line, text, count)`. `Type::method` also
    matches `.method(`, since that is how most call sites read once the receiver has a type,
    and `Type::function` does not, since an associated function has no receiver to be called on.

    Occurrences rather than lines. Two uses on one line are two uses, and rustfmt reflowing
    one call across two lines is still one, which is what lets an allowlist pin a count and
    survive a formatting change.

    Every form is matched on the whole name rather than on a prefix. A guard named `vouch`
    matching `fn vouching_for_one_command` would report a renamed symbol as present, which is the
    one answer this check must never give, and `Labelled::new` matching `Labelled::new_unchecked`
    would blame a use of the one symbol that was not used. For a qualified guard the file has to
    name the qualifier too, or be the file the module is: an unrelated `fn present` in another
    crate is not `Policy::present`, and counting it would put a file in the allowlist that never
    touches a label. For an associated function that is not enough, because a file using
    `Labelled` says `fn new` for reasons of its own, so there the definition counts at the one
    line that defines it.

    A qualified guard whose qualifier defines the name nowhere has no uses at all, whoever else
    in the tree spells a method that way. Otherwise a renamed method reads as present and takes
    another type's call sites with it, which is both the one answer this check must never give
    and the list a spec reviewer is handed as the symbol's uses."""
    parts = symbol.split("::")
    bare = parts[-1]
    qualifier = parts[0] if len(parts) > 1 else None
    associated = None
    if qualifier:
        owned = owned_definitions(bare, qualifier, sources)
        if not owned:
            return []
        associated = associated_sites(owned)
    named = re.compile(rf"\b{re.escape(symbol)}\b")
    definition = definition_of(bare)
    call = f".{bare}("
    hits = []
    for path, lines in sources.items():
        code = strip_comments(lines)
        owns = (
            qualifier is None
            or its_own_file(path, qualifier)
            or any(qualifier in line for line in code)
        )
        for number, raw in enumerate(code, start=1):
            count = len(named.findall(raw)) if symbol in raw else 0
            if associated is not None:
                count += (path, number) in associated
            else:
                count += raw.count(call)
                if owns:
                    count += len(definition.findall(raw))
            if count:
                hits.append((str(path), number, raw.strip(), count))
    return hits


def check_guards(spec, sources):
    """A guarded symbol exists, and where the entry pins its call sites, they are the sites
    it has. Presence alone catches a rename and nothing else: a new use of an escape hatch
    reads as ordinary code, which is how one lands without anybody deciding it should."""
    entries = spec.front.get("guards", [])
    allowlists = spec.allowlists
    pinned = spec.pinned_guards
    if pinned and len(pinned) != len(entries):
        yield finding(
            spec.rel,
            ERROR,
            "guard-sites-partial",
            "some `guards` entries pin their call sites and some do not",
            fix="an unpinned entry beside pinned ones reads as though it were checked too",
        )

    for symbol in spec.guards:
        sites = guard_sites(symbol, sources)
        if not sites:
            parts = symbol.split("::")
            # A qualified name reaching here is one its qualifier does not define, which another
            # type spelling the bare name the same way does not answer. Saying which half is
            # missing is the difference between looking for a rename and looking for a symbol.
            said = (
                f"`guards` names `{symbol}`, and no `{parts[0]}` in crates/ defines `{parts[-1]}`"
                if len(parts) > 1
                else f"`guards` names `{symbol}`, which appears nowhere in crates/"
            )
            yield finding(
                spec.rel,
                ERROR,
                "guard-missing",
                said,
                fix="a guarded symbol that was renamed stops being review-required silently",
            )
            continue
        if symbol in allowlists:
            yield from check_allowlist(spec, symbol, allowlists[symbol], sites)


def check_allowlist(spec, symbol, listed, sites):
    """Compare a pinned `sites:` list against the tree, file by file.

    The count has to match rather than merely not be exceeded. A ceiling left above the real
    figure hands back the slots that were freed, so a removed use silently pays for a new one,
    and the recorded number stops being a fact about the tree."""
    if not isinstance(listed, list):
        yield finding(
            spec.rel,
            ERROR,
            "guard-sites-malformed",
            f"`{symbol}` has a `sites:` that is not a list of `path: count` items",
        )
        return

    allowed = {}
    unusable = set()
    for item in listed:
        head, separator, tail = item.rpartition(":")
        # With no separator the whole item is the path and the count is missing, rather than
        # the other way round, so that the file below is still recognised as one that was named.
        path, count = (head.strip(), tail.strip()) if separator else (item.strip(), "")
        problem = None
        if not path or not count.isdigit():
            problem = "is not `path: count`"
        elif count == "0":
            problem = "pins no sites, which is what leaving the path out says"
        elif path in allowed or path in unusable:
            problem = "names a path the list already pins"
        if problem:
            # The path is remembered as unusable so that the comparison below stays quiet about
            # it. One typo should read as one problem, not as the file having gone unlisted.
            unusable.add(path)
            allowed.pop(path, None)
            yield finding(
                spec.rel,
                ERROR,
                "guard-sites-malformed",
                f"`{symbol}` pins `{item}`, which {problem}",
            )
            continue
        allowed[path] = int(count)

    found = {}
    where = {}
    for path, number, _, count in sites:
        found[path] = found.get(path, 0) + count
        where.setdefault(path, []).append(number)

    for path in sorted((set(allowed) | set(found)) - unusable):
        actual = found.get(path, 0)
        numbers = where.get(path, [])
        lines = ", ".join(str(n) for n in numbers[:12])
        if len(numbers) > 12:
            lines += f", and {len(numbers) - 12} more"
        if path not in allowed:
            yield finding(
                spec.rel,
                ERROR,
                "guard-site-unlisted",
                f"`{symbol}` is used in `{path}`, which its `sites:` list does not name",
                evidence=f"{path}:{lines}",
                fix=f"record `{path}: {actual}`, or use the gate that already covers this",
            )
        elif actual != allowed[path]:
            yield finding(
                spec.rel,
                ERROR,
                "guard-site-count",
                f"`{symbol}` is pinned at {allowed[path]} uses in `{path}` and has {actual}",
                evidence=f"{path}:{lines}" if lines else f"{path}: no uses left",
                fix=f"a use of this symbol is review-required: record `{path}: {actual}`",
            )


def check_isolation(spec, prefixes):
    """Each spec stands alone: a clause id is only ever cited inside its own file."""
    for other in prefixes:
        if other == spec.id:
            continue
        for number, raw in enumerate(spec.lines, start=1):
            for token in ("`" + other + "-", " " + other + "-", "(" + other + "-"):
                if token in raw:
                    yield finding(
                        spec.rel,
                        ERROR,
                        "cross-spec-citation",
                        f"cites `{other}`'s clause ids; a reader landing here has no idea what they are",
                        evidence=f"{spec.rel}:{number}",
                        fix="state the fact in a few words, and link the other file by name",
                    )
                    break
            else:
                continue
            break


def check_prose(spec):
    for number, raw in enumerate(spec.lines, start=1):
        if EM_DASH in raw:
            yield finding(
                spec.rel,
                ERROR,
                "em-dash",
                "em-dash: a comma, a colon, parentheses, or two sentences will do the job",
                evidence=f"{spec.rel}:{number}",
            )


def check_readme(specs):
    if not README.exists():
        yield finding(str(README), ERROR, "readme-missing", "docs/specs/README.md is not there")
        return
    text = README.read_text(encoding="utf-8")
    rows = {}
    for raw in text.split("\n"):
        if not raw.startswith("|"):
            continue
        cells = [cell.strip() for cell in raw.strip("|").split("|")]
        if len(cells) < 4 or not cells[0].startswith("["):
            continue
        link = cells[0].split("(", 1)[1].rstrip(")") if "(" in cells[0] else cells[0]
        rows[link] = (cells[1].strip("`"), cells[2])

    for spec in specs:
        link = str(spec.path.relative_to(SPEC_DIR))
        if link not in rows:
            yield finding(
                str(README),
                ERROR,
                "readme-unlisted",
                f"{link} is a spec but has no row in the table",
                fix="an unlisted spec is one nobody finds, and its topic reads as ordinary code",
            )
            continue
        listed_id, listed_count = rows.pop(link)
        if listed_id != spec.id:
            yield finding(
                str(README),
                ERROR,
                "readme-wrong-id",
                f"{link} is listed as `{listed_id}` and its front matter says `{spec.id}`",
            )
        live = len([c for c in spec.clauses if not c.withdrawn])
        if listed_count.isdigit() and int(listed_count) != live:
            yield finding(
                str(README),
                ERROR,
                "readme-wrong-count",
                f"{link} is listed with {listed_count} clauses and has {live}",
            )

    for link in rows:
        yield finding(
            str(README),
            ERROR,
            "readme-phantom",
            f"the table lists {link}, which is not a spec file",
        )


def load_sources():
    return {
        path: path.read_text(encoding="utf-8", errors="replace").split("\n")
        for path in sorted(Path("crates").rglob("*.rs"))
    }


def changed_files(base):
    for command in (
        ["git", "diff", "--name-only", f"{base}...HEAD"],
        ["git", "diff", "--name-only", "HEAD"],
        ["git", "diff", "--name-only", "--cached"],
    ):
        try:
            out = subprocess.run(command, capture_output=True, text=True, check=False).stdout
        except OSError:
            continue
        for line in out.split("\n"):
            if line.strip():
                yield line.strip()


def spec_names(spec):
    """Every form that names one spec on the command line: its id, its file name, and its path
    both under `docs/specs` and from the repository root, each of the three with `.md` optional.

    The path is the form the tree hands a person: `grep -rl SEARCH-9 docs/specs` prints
    `docs/specs/tools/search.md`, and the table in `AGENTS.md` links the same. Matching is exact
    against this set rather than a suffix test, so a directory typed in part names no spec instead
    of quietly resolving to one."""
    rel = spec.path.as_posix()
    prefix = f"{SPEC_DIR.as_posix()}/"
    forms = {spec.id, spec.path.name, rel}
    if rel.startswith(prefix):
        forms.add(rel[len(prefix) :])
    forms |= {form.removesuffix(".md") for form in forms}
    return {form.lower() for form in forms if form}


def select(specs, selectors, changed_base):
    if selectors:
        wanted = {s.lower() for s in selectors}
        chosen = [spec for spec in specs if spec_names(spec) & wanted]
        missing = wanted - {name for spec in chosen for name in spec_names(spec)}
        return chosen, sorted(missing)
    if changed_base is not None:
        touched = set(changed_files(changed_base))
        chosen = []
        for spec in specs:
            # A pinned path counts as well as a governed one. The files a guard allowlist pins
            # are mostly not the files the spec governs, so selecting on `governs` alone would
            # leave the branch run silent about the one edit the allowlist exists to catch.
            patterns = list(spec.governs) + [
                item.rpartition(":")[0].strip()
                for sites in spec.allowlists.values()
                if isinstance(sites, list)
                for item in sites
            ]
            if spec.rel in touched or any(
                any(fnmatch(f, pattern) for f in touched) for pattern in patterns if pattern
            ):
                chosen.append(spec)
        return chosen, []
    return list(specs), []


PROMPT = """\
# Conformance review: {spec_name}, clauses {clause_range}

You are checking that the **implementation matches the spec**, not the other way round.

## The one direction this review runs in

When the code and the spec disagree, **the code is wrong**. Never propose editing a clause
to describe what the code does, never soften a clause, and never report "the spec is
unrealistic" as a finding. If an implementation cannot satisfy a clause, the implementation
is the finding. Proposing spec text is out of scope for this review entirely: another
process, with human review, changes specs.

Clauses describe behaviour, not implementation. A clause is satisfied by behaviour that
holds, not by a function that happens to be named after it.

## The rule that outranks every clause

The driver and the planner never have untrusted content in their context. The driver is
`bravebot-core` and `bravebot-agent` both; the planner is the model. The driver may carry
untrusted content and hand it to an effect, but may not branch on it: no `if`, `match`,
comparison, or early return whose condition derives from untrusted bytes. Moving such a
branch from `bravebot-agent` into `bravebot-core` does not fix it.

A witness is not permission to inspect. A `declassify` outside `Policy::present`,
`Policy::render_in_place` (or its two-input form `Policy::render_pair_in_place`),
`Policy::read_trusted_content` and `Policy::read_planner_argument` is almost certainly a
violation. Constructing a `Labelled`
by hand to give a value a better label than its inputs had is laundering.

The deliberate exceptions are listed under "Known costs" in docs/specs/labels.md. Anything
not listed there is a violation, whatever the comment beside it says.

Report a breach of this rule at severity `error`, whether or not a clause names it.

## What you are reviewing

Spec file: `{spec_path}`
Clauses in your scope: {clause_ids}

Read these yourself, with your own tools. They are named rather than pasted so you can read
what the clauses actually need.

Governed source files (this spec decides these paths):
{governed}

Guarded symbols and every place they are used (each use is review-required). Comments are not
listed, so a symbol you find named in prose is not missing from this list:
{guards}

Tests the clauses in your scope name, already confirmed to exist:
{tests}

## The spec, in full

Read every clause for context. Report only on the ones in your scope.

```markdown
{spec_text}
```

## The job

For each clause in your scope:

1. Read the governed source until you can say what the code actually does, in the terms
   the clause uses. Read the named tests too.
2. Decide one of:
   - `conforms`: the behaviour the clause describes is the behaviour the code has.
   - `violation`: the code does something the clause forbids, or does not do something the
     clause requires. This is a finding.
   - `untested`: the behaviour looks right, but the named tests do not actually pin it. A
     test that would still pass against the buggy code does not pin anything. This is a
     finding at severity `warning`, and the fix is a test, not a spec edit.
   - `unclear`: you could not tell from the governed files. Say what you would need. Not a
     finding, but say so honestly rather than guessing `conforms`.
3. Every `violation` needs a concrete failure: the input or state, the path through the
   code, and the outcome the clause forbids. `file:line` for each step. A finding you
   cannot walk somebody through is a finding you have not verified, and it does not go in.
4. On a `violation`, say which of two things the code does: attempts the behaviour and gets
   it wrong, or does not attempt it at all. Set `absent` only for the second. Nothing is
   broken today where nothing was built, and whoever picks the issue up needs to know which
   of the two they are taking on before they open the file.
5. Where the wrong behaviour is something a person could look at, a screen drawn wrongly
   or a prompt that says the wrong thing, put in `screen` how to reach it: what to type,
   in order, from a fresh session. Leave the field out otherwise, and never guess at one.
   You do not run anything; that field is a script for whoever files this, so that the
   bug report can show the screen instead of describing it.

Check the whole clause, including the parts stated in the "Why" paragraph where the clause
has one, and any table a clause carries: a table row is part of that clause.

Before you report a violation, look for the code that would refute it. Structural
guarantees in this repository are often enforced somewhere other than the place you are
reading, in a type that offers no way to do the wrong thing. Take the refutation seriously.
False findings on a spec check are expensive: they get somebody to weaken a guarantee that
was already holding.

## Output

Write JSON to `{results_file}` and nothing else to stdout:

```json
{{
  "spec": "{spec_name}",
  "clauses": [
    {{
      "clause": "{example_clause}",
      "verdict": "conforms | violation | untested | unclear",
      "summary": "one sentence, only when the verdict is not conforms",
      "severity": "error | warning",
      "evidence": ["crates/.../file.rs:123 what is there"],
      "failure": "input or state, path through the code, outcome the clause forbids",
      "absent": "true only where nothing in the code attempts the behaviour; leave it out otherwise",
      "fix": "what the implementation should do instead, in a sentence",
      "screen": "how to reach the screen this shows up on, only where a person could look at it"
    }}
  ]
}}
```

One entry per clause in your scope, including the ones that conform. No prose outside the
file. Do not edit any file.
"""


def build_prompt(spec, clauses, sources, crates, index, results_file):
    governed = "\n".join(
        f"- `{pattern}`" + ("" if Path(pattern).exists() else "  (missing)")
        for pattern in spec.governs
    ) or "- (none)"

    guard_lines = []
    for symbol in spec.guards:
        sites = guard_sites(symbol, sources)
        uses = sum(count for _, _, _, count in sites)
        guard_lines.append(f"- `{symbol}`: {uses} uses")
        for path, number, _, _ in sites[:40]:
            guard_lines.append(f"    - {path}:{number}")
        if len(sites) > 40:
            guard_lines.append(f"    - ... and {len(sites) - 40} more, grep for it")
    guards = "\n".join(guard_lines) or "- (none)"

    test_lines = []
    for clause in clauses:
        for reference in clause.verified_by:
            if reference == "none" or reference.startswith("by-construction"):
                test_lines.append(f"- {clause.id}: `{reference}` (nothing to read)")
                continue
            status, detail = index.resolve(reference, crates)
            location = detail if status in ("ok", "moved") else "unresolved"
            test_lines.append(f"- {clause.id}: `{reference}` at {location}")
    tests = "\n".join(test_lines) or "- (none)"

    ids = [clause.id for clause in clauses]
    return PROMPT.format(
        spec_name=spec.name,
        spec_path=spec.rel,
        clause_range=f"{ids[0]} to {ids[-1]}" if len(ids) > 1 else ids[0],
        clause_ids=", ".join(f"`{i}`" for i in ids),
        governed=governed,
        guards=guards,
        tests=tests,
        spec_text=spec.path.read_text(encoding="utf-8"),
        results_file=results_file,
        example_clause=ids[0],
    )


def render(findings, chosen, strict):
    errors = [f for f in findings if f["severity"] == ERROR]
    warnings = [f for f in findings if f["severity"] == WARNING]
    lines = []
    by_spec = {}
    for item in findings:
        by_spec.setdefault(item["spec"], []).append(item)
    for spec in sorted(by_spec):
        lines.append(f"\n{spec}")
        for item in by_spec[spec]:
            mark = "error" if item["severity"] == ERROR else "warn "
            where = f"  [{item['evidence']}]" if item.get("evidence") else ""
            lines.append(f"  {mark}  {item['summary']}{where}")
            if item.get("fix"):
                lines.append(f"         {item['fix']}")
    clauses = sum(len(spec.clauses) for spec in chosen)
    lines.append("")
    lines.append(
        f"{len(chosen)} specs, {clauses} clauses: {len(errors)} errors, {len(warnings)} warnings"
    )
    if warnings and not strict:
        lines.append("warnings do not fail this check; --strict makes them fail")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "specs", nargs="*", help="spec paths, file names, stems, or ids; default all"
    )
    parser.add_argument("--mechanical-only", action="store_true", help="skip the review pass")
    parser.add_argument("--changed", nargs="?", const="main", default=None, metavar="BASE")
    parser.add_argument("--strict", action="store_true", help="warnings fail too")
    parser.add_argument(
        "--write-unverified", action="store_true", help=f"write {UNVERIFIED_FILE} from the specs"
    )
    parser.add_argument("--work-dir", default=None)
    parser.add_argument("--chunk-size", type=int, default=6, help="clauses per reviewer")
    parser.add_argument("--json", action="store_true", help="findings as JSON on stdout")
    args = parser.parse_args()

    if args.write_unverified and partial_selection(args.specs, args.changed):
        print("the unverified list requires every spec: drop the filter", file=sys.stderr)
        return 2

    root = Path(__file__).resolve().parents[3]
    os.chdir(root)
    if not SPEC_DIR.is_dir():
        print(f"no {SPEC_DIR} under {root}", file=sys.stderr)
        return 2

    specs = load_specs()
    if args.write_unverified:
        lines = unverified_clauses(specs, TestIndex(), crate_directories())
        UNVERIFIED_FILE.write_text(render_unverified(lines), encoding="utf-8")
        print(f"{UNVERIFIED_FILE}: {len(lines)} clauses")
        return 0

    chosen, unknown = select(specs, args.specs, args.changed)
    findings = [
        finding(str(SPEC_DIR), ERROR, "unknown-spec", f"no spec named `{name}`")
        for name in unknown
    ]

    sources = load_sources()
    crates = crate_directories()
    index = TestIndex()
    prefixes = {spec.id for spec in specs if spec.id}

    for spec in chosen:
        findings.extend(check_front_matter(spec))
        findings.extend(check_clause_numbering(spec))
        findings.extend(check_coverage(spec, index, crates))
        findings.extend(check_anchors(spec))
        findings.extend(check_governs(spec))
        findings.extend(check_guards(spec, sources))
        findings.extend(check_isolation(spec, prefixes))
        findings.extend(check_prose(spec))
        findings.extend(check_documentation(spec))
    # Both of these are about the whole tree rather than one spec, so a run given a filter has
    # not read enough to judge either: the table would look short of rows, and the list short
    # of clauses.
    if len(chosen) == len(specs):
        findings.extend(check_readme(specs))
        findings.extend(check_unverified_file(specs, index, crates))

    failed = any(f["severity"] == ERROR for f in findings) or (
        args.strict and bool(findings)
    )

    if args.mechanical_only or args.json:
        if args.json:
            print(json.dumps({"findings": findings}, indent=2))
        else:
            print(render(findings, chosen, args.strict))
        return 1 if failed else 0

    work_dir = Path(args.work_dir or tempfile.mkdtemp(prefix="check-spec-"))
    work_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for spec in chosen:
        reviewable = [c for c in spec.clauses if not c.withdrawn]
        if not reviewable:
            continue
        spec_dir = work_dir / (spec.id or spec.path.stem)
        spec_dir.mkdir(parents=True, exist_ok=True)
        chunks = [
            reviewable[i : i + args.chunk_size]
            for i in range(0, len(reviewable), args.chunk_size)
        ]
        prompts = []
        for number, clauses in enumerate(chunks, start=1):
            results_file = spec_dir / f"chunk{number}_results.json"
            prompt_file = spec_dir / f"chunk{number}_prompt.md"
            prompt_file.write_text(
                build_prompt(spec, clauses, sources, crates, index, results_file), encoding="utf-8"
            )
            prompts.append(
                {
                    "prompt_file": str(prompt_file),
                    "results_file": str(results_file),
                    "clauses": [c.id for c in clauses],
                }
            )
        entries.append(
            {
                "spec": spec.name,
                "path": spec.rel,
                "id": spec.id,
                "clauses": len(reviewable),
                "reviewer_prompts": prompts,
            }
        )

    manifest = {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "root": str(root),
        "strict": args.strict,
        "mechanical_findings": findings,
        "mechanical_failed": failed,
        "specs": entries,
        "progress_lines": [
            f"check-spec: {len(entries)} specs, "
            f"{sum(len(e['reviewer_prompts']) for e in entries)} reviewers, "
            f"{len(findings)} mechanical findings"
        ],
    }
    manifest_path = work_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(render(findings, chosen, args.strict), file=sys.stderr)
    print(json.dumps({"work_dir": str(work_dir), "manifest": str(manifest_path)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
