#!/usr/bin/env python3
"""Holds every catalog in crates/i18n/locales to a written record of what it is missing.

A translation with fewer messages than the reference builds, and what it lacks is shown in English.
That is deliberate: a catalog nobody could use until it was finished would never be started. The
cost of it is that a message can ship untranslated and nothing says so. The build script counts the
gap, but it prints a warning, and a warning is silent on a cached build and does not fail a green
job.

So the gap is not what this gates on. An unrecorded gap is. untranslated-messages.txt lists the
messages each catalog is knowingly missing, and this fails while the file and the catalogs disagree,
in either direction: a gap nobody wrote down, and a line that is no longer true. Adding a message
without translating it is then a line in a diff rather than a warning nobody has to read.

The same shape as agents/unverified-clauses.txt and `make check-spec`, for the same reason.
"""

import argparse
import re
import sys
from pathlib import Path

LOCALES = Path(__file__).resolve().parent.parent / "crates/i18n/locales"
RECORD = Path(__file__).resolve().parent / "untranslated-messages.txt"
REFERENCE = "en-US"

# A message id at column zero. Continuation lines and select variants are indented, which is what
# makes this safe to anchor: see locales/README.md for the subset of Fluent in play. The space
# around the equals is this file's habit rather than the format's, and the build trims it, so a
# catalog that spells it differently still compiles and has to be counted.
MESSAGE = re.compile(r"^([a-z][a-z0-9-]*)[ \t]*=")

HEADER = """\
# Messages a translation does not have, which are shown in the reference language instead.
# Generated by make write-untranslated. Translate the message rather than editing here: while the
# two disagree, make check-locales fails, in either direction.
# Source: crates/i18n/locales/*.ftl, one line per gap, as locale:message-id.
# A new catalog starts by listing everything and shrinking this file, which is the point: a
# translation is useful from its first line, and what it still lacks is visible in a diff.
# No count is kept here. Two branches that each translate a message both edit the count, so it
# conflicts where the lists themselves merge cleanly, and a count nothing reads is wrong quietly.
"""


def parse(text):
    """The message ids in one catalog, and any line this parser did not recognise.

    A parser that quietly matches nothing reports every catalog complete forever, so a line at
    column zero that is neither blank, a comment, nor a message is returned rather than skipped.
    """
    ids, unrecognised = [], []
    for number, line in enumerate(text.split("\n"), 1):
        if not line.strip() or line.startswith("#") or line[:1].isspace():
            continue
        found = MESSAGE.match(line)
        if found:
            ids.append(found.group(1))
        else:
            unrecognised.append((number, line))
    return ids, unrecognised


def read_catalogs(directory):
    """Every catalog in the directory, by locale tag, with the reference first."""
    catalogs, unrecognised = {}, []
    for path in sorted(directory.glob("*.ftl")):
        ids, junk = parse(path.read_text(encoding="utf-8"))
        catalogs[path.stem] = ids
        unrecognised += [(path.name, number, line) for number, line in junk]
    return catalogs, unrecognised


def gaps(catalogs):
    """What each catalog other than the reference is missing from it, in reference order."""
    reference = catalogs[REFERENCE]
    return {
        tag: [message for message in reference if message not in set(ids)]
        for tag, ids in catalogs.items()
        if tag != REFERENCE
    }


def read_record(text):
    """The recorded gaps as a set of (locale, message) pairs."""
    recorded = set()
    for line in text.split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        tag, _, message = line.partition(":")
        recorded.add((tag, message))
    return recorded


def write_record(found):
    """The record file's contents for the gaps that are actually there."""
    lines = sorted(f"{tag}:{message}" for tag, missing in found.items() for message in missing)
    return HEADER + ("\n" + "\n".join(lines) + "\n" if lines else "")


def verdict(found, recorded, catalogs):
    """Every way the record and the catalogs disagree, as complaints to print.

    Both directions, because a record allowed to go stale becomes a graveyard that permits the next
    gap: an entry that is no longer missing has to be removed for the file to keep meaning anything.
    """
    complaints = []
    actual = {(tag, message) for tag, missing in found.items() for message in missing}

    for tag, message in sorted(actual - recorded):
        complaints.append(
            f"{tag}:{message} is missing from {tag}.ftl and is not in {RECORD.name}. "
            f"Translate it, or run make write-untranslated to record it."
        )

    reference = set(catalogs[REFERENCE])
    for tag, message in sorted(recorded - actual):
        if tag not in catalogs:
            why = f"there is no {tag}.ftl"
        elif message not in reference:
            why = f"{REFERENCE}.ftl has no message {message}"
        else:
            why = f"{tag}.ftl has it"
        complaints.append(
            f"{tag}:{message} is in {RECORD.name} but {why}. "
            f"Run make write-untranslated and commit what it writes."
        )
    return complaints


def report(catalogs, found):
    """What each catalog has of the reference, and what it is missing."""
    total = len(catalogs[REFERENCE])
    print(f"{REFERENCE}  {total} messages, the reference")
    for tag in sorted(found):
        missing = found[tag]
        print(f"{tag}  {total - len(missing)} of {total}")
        for message in missing:
            print(f"    missing: {message}")


# Each case is one thing a wrong parser would get wrong: the shapes a catalog may take, and last
# the tripwire for this parser falling behind the format.
PARSE_CASES = [
    ("a message is found", "write-title = approve this write?", ["write-title"], 0),
    (
        "an indented continuation is not a message",
        "vouch-explained =\n    the model cannot read this file, so x = y is prose\n",
        ["vouch-explained"],
        0,
    ),
    (
        "a select variant is not a message",
        "count-rules = { $count ->\n    [one] { $count } rule\n   *[other] { $count } rules\n    }\n",
        ["count-rules"],
        0,
    ),
    ("a comment is not a message", "# write-title = no\n## A section\n", [], 0),
    (
        "the spacing around the equals is not the format",
        "write-title= a\nwrite-body  = b\nwrite-foot\t= c\n",
        ["write-title", "write-body", "write-foot"],
        0,
    ),
    ("an unrecognised line is reported", "Write-Title = no\n", [], 1),
]


def selftest():
    """Prove the parse and the verdict on inputs whose answer is known.

    A gate that is quietly wrong is worse than no gate: this one's whole claim is that an
    untranslated message cannot reach main unnoticed, and a parser that returns nothing makes every
    catalog look complete. So each case here is one thing that has to hold for the claim to.
    """
    checks = []
    for name, text, ids, junk in PARSE_CASES:
        got_ids, got_junk = parse(text)
        checks.append((f"parse: {name}", got_ids == ids, got_ids))
        checks.append((f"parse: {name}, junk", len(got_junk) == junk, got_junk))

    catalogs = {REFERENCE: ["one", "two"], "fr": ["one"], "de": ["one", "two"]}
    found = gaps(catalogs)
    checks.append(("gaps: found in reference order", found == {"fr": ["two"], "de": []}, found))

    cases = [
        ("an unrecorded gap fails", set(), 1),
        ("a recorded gap passes", {("fr", "two")}, 0),
        ("a stale entry fails", {("fr", "two"), ("de", "two")}, 1),
        ("an unknown message fails", {("fr", "two"), ("fr", "three")}, 1),
        ("an unknown locale fails", {("fr", "two"), ("es", "one")}, 1),
    ]
    for name, recorded, expected in cases:
        got = verdict(found, recorded, catalogs)
        checks.append((f"verdict: {name}", len(got) == expected, got))

    complete = {REFERENCE: ["one"], "fr": ["one"]}
    got = verdict(gaps(complete), set(), complete)
    checks.append(("verdict: a complete catalog and an empty record pass", got == [], got))

    written = write_record({"fr": ["two"], "de": []})
    checks.append(("write: one gap, one line", written.endswith("\nfr:two\n"), written))
    checks.append(
        ("write: no gaps, no lines", write_record({"fr": []}) == HEADER, write_record({"fr": []}))
    )

    broke = [(claim, got) for claim, held, got in checks if not held]
    for claim, got in broke:
        print(f"selftest: {claim}, got {got!r}", file=sys.stderr)
    if broke:
        print(f"{len(broke)} of {len(checks)} checks failed", file=sys.stderr)
        return 1
    print(f"selftest: {len(checks)} checks passed")
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Hold the message catalogs to untranslated-messages.txt.",
    )
    ap.add_argument(
        "--report",
        action="store_true",
        help="print what each catalog has of the reference, failing on no gap it finds",
    )
    ap.add_argument(
        "--write", action="store_true", help="rewrite untranslated-messages.txt from the catalogs"
    )
    ap.add_argument(
        "--selftest", action="store_true", help="check the parse and the verdict, reading no catalog"
    )
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    catalogs, unrecognised = read_catalogs(LOCALES)
    if REFERENCE not in catalogs:
        print(f"{LOCALES}/{REFERENCE}.ftl is the reference and is not there", file=sys.stderr)
        return 1

    # Before anything else: a line this parser cannot read means its answer about what is missing is
    # not worth having. The build script is what decides whether a catalog is valid; this only says
    # that the counting below did not silently skip part of a file.
    for name, number, line in unrecognised:
        print(f"{name}:{number}: not a comment or a message: {line!r}", file=sys.stderr)
    if unrecognised:
        print(
            "check-locales cannot count a file it cannot read. If the format gained a shape, "
            "teach contrib/check-locales.py about it.",
            file=sys.stderr,
        )
        return 1

    found = gaps(catalogs)

    if args.report:
        report(catalogs, found)
        return 0

    if args.write:
        RECORD.write_text(write_record(found), encoding="utf-8")
        counted = sum(len(missing) for missing in found.values())
        print(f"{RECORD.name}: {counted} gap{'' if counted == 1 else 's'}")
        return 0

    # A missing record reads as an empty one rather than as an error, so a checkout that has lost
    # the file still fails on the gaps themselves instead of on the file.
    text = RECORD.read_text(encoding="utf-8") if RECORD.exists() else ""
    complaints = verdict(found, read_record(text), catalogs)
    for complaint in complaints:
        print(complaint, file=sys.stderr)
    if complaints:
        return 1
    counted = sum(len(missing) for missing in found.values())
    print(
        f"check-locales: {len(catalogs) - 1} translation"
        f"{'' if len(catalogs) == 2 else 's'} of {len(catalogs[REFERENCE])} messages, "
        f"{counted} recorded gap{'' if counted == 1 else 's'}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
