//! Compiles `locales/*.ftl` into the Rust the crate exposes.
//!
//! Doing this at build time rather than at start is what makes a missing message or a misspelled
//! argument a compilation error instead of a string that reads wrong on somebody's screen. It also
//! means no catalog text is parsed while the agent is running: the running process holds finished
//! `&'static str`s and nothing that interprets them.
//!
//! `en-US` is the reference. It owns the set of messages and the name and kind of every argument,
//! so a translation can never change what a call site has to pass.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

// The catalog format and the code generator, in the modules the crate has them in: a path
// written in one of them has to mean the same thing here as it does there.
mod catalog {
    include!("src/catalog.rs");
}
mod generate {
    include!("src/generate.rs");
}

use crate::catalog::*;
use crate::generate::*;

// Flat, because the plural rules are called by the code this writes rather than by this, and a
// module of its own would make the one function the build script does call look unused.
include!("src/plural.rs");

/// The locale every other one is checked against and falls back to.
const REFERENCE: &str = "en-US";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/catalog.rs");
    println!("cargo:rerun-if-changed=src/plural.rs");
    println!("cargo:rerun-if-changed=src/generate.rs");
    println!("cargo:rerun-if-changed=locales");

    let locales = load();
    let reference = locales
        .iter()
        .find(|l| l.tag == REFERENCE)
        .unwrap_or_else(|| {
            panic!("locales/{REFERENCE}.ftl is the reference catalog and must exist")
        });

    check(&locales, reference);

    let mut out = String::from("// Generated by build.rs from locales/*.ftl. Do not edit.\n");
    out.push_str(&locale_enum(&locales));
    out.push_str(&messages(&locales, reference));
    out.push_str(&macro_arms(reference));

    let path = Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("messages.rs");
    fs::write(&path, out).expect("write the generated catalog");
}

/// Every catalog in `locales/`, reference first so generated indices are stable.
fn load() -> Vec<Catalog> {
    let dir = Path::new("locales");
    let mut found: Vec<Catalog> = Vec::new();

    let entries = fs::read_dir(dir).expect("locales/ exists");
    let mut paths: Vec<_> = entries
        .map(|e| e.expect("read locales/").path())
        .filter(|p| p.extension().is_some_and(|e| e == "ftl"))
        .collect();
    paths.sort();

    for path in paths {
        let tag = path
            .file_stem()
            .expect("a .ftl file has a stem")
            .to_str()
            .expect("locale filenames are ASCII")
            .to_string();
        let (language, region) = match tag.split_once('-') {
            Some((language, region)) => (language, Some(region)),
            None => (tag.as_str(), None),
        };
        let well_formed = language.len() >= 2
            && language.len() <= 3
            && language.chars().all(|c| c.is_ascii_lowercase())
            && region.is_none_or(|r| r.len() == 2 && r.chars().all(|c| c.is_ascii_uppercase()));
        assert!(
            well_formed,
            "locales/{tag}.ftl is not named for a locale: use `fr.ftl` or `fr-CA.ftl`"
        );

        let source = fs::read_to_string(&path).expect("read a catalog");
        let parsed = parse(&source).unwrap_or_else(|e| panic!("locales/{tag}.ftl: {e}"));

        let mut messages = BTreeMap::new();
        for message in parsed {
            messages.insert(message.id.clone(), message);
        }

        found.push(Catalog {
            tag: tag.clone(),
            language: language.to_string(),
            variant: camel_case(&tag.to_lowercase()),
            messages,
        });
    }

    // The reference leads so `Locale as usize` indexes the per-message tables with the fallback
    // at a known position.
    found.sort_by_key(|l| (l.tag != REFERENCE, l.tag.clone()));
    found
}

/// Everything a translation is not allowed to do, checked before a line is generated.
fn check(locales: &[Catalog], reference: &Catalog) {
    for locale in locales {
        for (id, message) in &locale.messages {
            let Some(source) = reference.messages.get(id) else {
                panic!(
                    "locales/{}.ftl line {}: `{id}` is in no other catalog. A message is added to \
                     locales/{REFERENCE}.ftl first, so the call sites exist before a translation \
                     of them does",
                    locale.tag, message.line
                );
            };

            let expected = arguments(&source.value);
            for (name, selects) in arguments(&message.value) {
                let Some((_, source_selects)) = expected.iter().find(|(e, _)| *e == name) else {
                    panic!(
                        "locales/{}.ftl line {}: `{id}` reads `${name}`, which the message does \
                         not take",
                        locale.tag, message.line
                    );
                };
                assert!(
                    !selects || *source_selects,
                    "locales/{}.ftl line {}: `{id}` puts `${name}` in a plural select, but the \
                     message in locales/{REFERENCE}.ftl does not. The argument's Rust type comes \
                     from the reference, so give the reference the plural form first",
                    locale.tag,
                    message.line
                );
            }

            let has_select = matches!(message.value, Value::Select { .. });
            assert!(
                !has_select || is_known(&locale.language),
                "locales/{}.ftl line {}: `{id}` selects on a plural, and no plural rule for `{}` \
                 is written in crates/i18n/src/plural.rs. Add its rule there rather than letting \
                 it take English's",
                locale.tag,
                message.line,
                locale.language
            );
        }

        let missing = reference
            .messages
            .keys()
            .filter(|id| !locale.messages.contains_key(*id))
            .count();
        if missing > 0 && locale.tag != REFERENCE {
            println!(
                "cargo:warning=locales/{}.ftl is missing {missing} of {} messages, which will \
                 show in {REFERENCE}",
                locale.tag,
                reference.messages.len()
            );
        }
    }
}

fn locale_enum(locales: &[Catalog]) -> String {
    let mut out = String::from(
        "\n/// A catalog that shipped with this build.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n\
         pub enum Locale {\n",
    );
    for locale in locales {
        out.push_str(&format!(
            "    /// `{}`\n    {},\n",
            locale.tag, locale.variant
        ));
    }
    out.push_str("}\n\n");

    out.push_str("impl Locale {\n    /// The BCP-47 tag this catalog is named for.\n");
    out.push_str("    pub fn tag(self) -> &'static str {\n        match self {\n");
    for locale in locales {
        out.push_str(&format!(
            "            Locale::{} => {:?},\n",
            locale.variant, locale.tag
        ));
    }
    out.push_str("        }\n    }\n\n");

    out.push_str("    /// The language subtag, which is what plural rules are keyed on.\n");
    out.push_str("    pub fn language(self) -> &'static str {\n        match self {\n");
    for locale in locales {
        out.push_str(&format!(
            "            Locale::{} => {:?},\n",
            locale.variant, locale.language
        ));
    }
    out.push_str("        }\n    }\n}\n\n");

    out.push_str("/// Every catalog, reference first.\npub const LOCALES: &[Locale] = &[\n");
    for locale in locales {
        out.push_str(&format!("    Locale::{},\n", locale.variant));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// The catalog a request nothing else matches falls back to.\n\
         pub const DEFAULT: Locale = Locale::{};\n",
        locales[0].variant
    ));
    out
}

/// One `t!` arm per message, which is what makes an unknown key fail to compile.
///
/// There is deliberately no arm taking a runtime key. A message chosen by a value rather than by
/// a name written in the source would be a decision, and content the agent was handed is exactly
/// what must never make one.
fn macro_arms(reference: &Catalog) -> String {
    let mut out = String::from(
        "\n/// Look up a message by the name it has in the catalog.\n\
         ///\n\
         /// ```ignore\n\
         /// t!(confirm_write_title)\n\
         /// t!(status_turns, count = turns)\n\
         /// ```\n\
         #[macro_export]\nmacro_rules! t {\n",
    );
    for (id, message) in &reference.messages {
        let arm = snake_case(id);
        if arguments(&message.value).is_empty() {
            out.push_str(&format!(
                "    ({arm}) => {{ $crate::messages::{arm}() }};\n"
            ));
        } else {
            out.push_str(&format!(
                "    ({arm} $(, $field:ident = $value:expr)* $(,)?) => {{\n        \
                 $crate::messages::{} {{ $($field: $value),* }}.render()\n    }};\n",
                camel_case(id)
            ));
        }
    }
    out.push_str("}\n");
    out
}
